apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
configMapGenerator:
- behavior: merge
  files:
  - dynamic.yaml=./proxy-config/dynamic.yaml
  - traefik.yaml=./proxy-config/traefik.yaml
  name: traefik-sidecar-config
  options:
    disableNameSuffixHash: true
