version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directories:
  - "/e2e"
  - "/operator"
  - "/server"
  groups:
    kubernetes:
      patterns:
      - "k8s.io/*"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directories:
  - "/hack/tools/golang-ci"
  - "/hack/tools/kustomize"
  - "/hack/tools/mockgen"
  - "/hack/tools/yq"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
