apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspace-reader
rules:
- apiGroups:
  - workspaces.konflux.io
  resources:
  - internalworkspaces
  verbs:
  - list
  - get
  - watch
  - update
