apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spacebinding-reader
  namespace: system
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - spacebindings
  verbs:
  - list
  - get
  - watch
