run:
  concurrency: 4
  timeout: 30m
  go: '1.22'
  issues-exit-code: 2
linters:
  enable:
  - gosimple
  - staticcheck
  - errcheck
  - govet
  - ineffassign
  - typecheck
  - unused
  - misspell
  - cyclop
  - errname
  - errorlint
  - ginkgolinter
  - gocritic
  - gofmt
  - gosec
  fast: true

# https://golangci-lint.run/usage/linters
linters-settings:
  cyclop:
    max-complexity: 20
    package-average: 10.0
  gocritic:
    disabled-checks:
      - ifElseChain
  gosec:
    excludes:
      - G601 # excluded as go 1.22 is used

output:
  formats:
    - format: colored-line-number   
  print-issued-lines: true
  print-linter-name: true
