---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - masteruserrecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - spacebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - toolchain.dev.openshift.com
  resources:
  - usersignups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workspaces.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspaces.io
  resources:
  - workspaces/finalizers
  verbs:
  - update
- apiGroups:
  - workspaces.io
  resources:
  - workspaces/status
  verbs:
  - get
  - patch
  - update
