# permissions for end users to edit workspaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: workspace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: workspaces
    app.kubernetes.io/part-of: workspaces
    app.kubernetes.io/managed-by: kustomize
  name: workspace-editor-role
rules:
- apiGroups:
  - workspaces.io
  resources:
  - workspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workspaces.io
  resources:
  - workspaces/status
  verbs:
  - get
