apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    provider: workspaces
    app: rest-api-server
  name: rest-api-server
  namespace: system
spec:
  host: ''
  port:
    targetPort: 8080
  to:
    kind: Service
    name: workspaces-rest-api-server
    weight: 100
  wildcardPolicy: None
