kind: Service
apiVersion: v1
metadata:
  name: rest-api-server
  namespace: system
  labels:
    provider: workspaces
    run: rest-api-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: rest-api-server
  type: ClusterIP
  sessionAffinity: None
