apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: system
  name: rest-api-server:workspace-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workspace-reader
subjects:
- kind: ServiceAccount
  name: rest-api-server
  namespace: system
