// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/konflux-workspaces/workspaces/server/core/workspace (interfaces: WorkspaceCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks_create.go -package=mocks . WorkspaceCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/konflux-workspaces/workspaces/server/api/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockWorkspaceCreator is a mock of WorkspaceCreator interface.
type MockWorkspaceCreator struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceCreatorMockRecorder
}

// MockWorkspaceCreatorMockRecorder is the mock recorder for MockWorkspaceCreator.
type MockWorkspaceCreatorMockRecorder struct {
	mock *MockWorkspaceCreator
}

// NewMockWorkspaceCreator creates a new mock instance.
func NewMockWorkspaceCreator(ctrl *gomock.Controller) *MockWorkspaceCreator {
	mock := &MockWorkspaceCreator{ctrl: ctrl}
	mock.recorder = &MockWorkspaceCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceCreator) EXPECT() *MockWorkspaceCreatorMockRecorder {
	return m.recorder
}

// CreateUserWorkspace mocks base method.
func (m *MockWorkspaceCreator) CreateUserWorkspace(arg0 context.Context, arg1 string, arg2 *v1alpha1.Workspace, arg3 ...client.CreateOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUserWorkspace", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserWorkspace indicates an expected call of CreateUserWorkspace.
func (mr *MockWorkspaceCreatorMockRecorder) CreateUserWorkspace(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWorkspace", reflect.TypeOf((*MockWorkspaceCreator)(nil).CreateUserWorkspace), varargs...)
}
