sequenceDiagram
  actor U as User

  participant KA as K8s ApiServer
  participant WO as Workspace Operator
  participant HO as Host Operator
  participant KAMC as Member Clusters

  U->>KA: Change Workspace Visibility to public
  KA-->>WO: Notify Workspace Event
  WO->>KA: Create Space Binding for public-viewer
  
  KA-->>HO: Notify Space Binding Event
  HO->>KAMC: Create RoleBindings for public-viewer
  
  U->>KA: Change Workspace Visibility to private
  KA-->>WO: Notify Workspace Event
  WO->>KA: Delete Space Binding for public-viewer
  
  KA-->>HO: Notify Space Binding Event
  HO->>KAMC: Delete RoleBindings for public-viewer

