run:
  concurrency: 4
  timeout: 30m
  go: '1.22'
  issues-exit-code: 2

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: "api/*"
      linters:
        - lll
    - path: "internal/*"
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

# https://golangci-lint.run/usage/linters
linters-settings:
  cyclop:
    max-complexity: 20
    package-average: 10.0
  gocritic:
    disabled-checks:
      - ifElseChain

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
