name: Server CI

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "server/**"
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Run tests
        # todo: set up code coverage?
        run: make -C server test

  lint-go:
    name: Lint code
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Determine golang-ci version
        id: golangci_version
        run: |
          echo "version=$(go mod edit -json | jq '.Require | map(select(.Path == "github.com/golangci/golangci-lint"))[].Version')" >> $GITHUB_OUTPUT

      - name: Lint with golang-ci
        uses: golangci/golangci-lint-action@v4
        with:
          version: ${{ steps.golangci_version.version }}
          working-directory: server

  lint-sh:
    permissions:
      security-events: write

    name: 
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          # we need a full history for differential shellcheck
          fetch-depth: 0

      - name: Differential ShellCheck
        id: ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ always() }}
        name: Upload ShellCheck defects
        uses: actions/upload-artifact@v4
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}
